<?php

namespace LaravelTolgee;

use LaravelTolgee\Commands\DeleteAllKeysCommand;
use LaravelTolgee\Commands\ImportKeysCommand;
use LaravelTolgee\Commands\SyncTranslationsCommand;
use LaravelTolgee\Integration\Tolgee;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class LaravelTolgeeServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('laravel-tolgee')
            ->hasConfigFile('tolgee')
            ->hasCommands([
                ImportKeysCommand::class,
                DeleteAllKeysCommand::class,
                SyncTranslationsCommand::class
            ]);
    }

    public function boot()
    {
        $this->app->singleton('tolgee', fn ($app) => app(Tolgee::class));
        return parent::boot(); // TODO: Change the autogenerated stub
    }

}
